name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ AKIAWBPQPR5DOM6HKGUP }}
          aws-secret-access-key: ${{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}}
          aws-region: us-west-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "4.60.0"

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply tfplan
        env:
          TF_INPUT: 0
          TF_VAR_aws_region: us-west-1
        with:
          args: "-auto-approve"
